# Configuration package
from .constants import (
    # Discord configuration
    DISCORD_BOT_TOKEN,
    DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET,
    DISCORD_PUBLIC_KEY,
    DISCORD_GUILD_ID,
    DISCORD_SUSPENDED_ROLE_ID,
    DISCORD_HANGAROUND_ROLE_ID,
    DISCORD_PROSPECT_ROLE_ID,
    # Application constants
    CHAPTERS,
    OFFICER_TITLES,
    AD_EDIT_TITLES,
    MANAGEABLE_TITLES,
    AVAILABLE_PERMISSIONS
)
